
//input ports
add mapped point clock clock -type PI PI
add mapped point nreset nreset -type PI PI
add mapped point a[31] a[31] -type PI PI
add mapped point a[30] a[30] -type PI PI
add mapped point a[29] a[29] -type PI PI
add mapped point a[28] a[28] -type PI PI
add mapped point a[27] a[27] -type PI PI
add mapped point a[26] a[26] -type PI PI
add mapped point a[25] a[25] -type PI PI
add mapped point a[24] a[24] -type PI PI
add mapped point a[23] a[23] -type PI PI
add mapped point a[22] a[22] -type PI PI
add mapped point a[21] a[21] -type PI PI
add mapped point a[20] a[20] -type PI PI
add mapped point a[19] a[19] -type PI PI
add mapped point a[18] a[18] -type PI PI
add mapped point a[17] a[17] -type PI PI
add mapped point a[16] a[16] -type PI PI
add mapped point a[15] a[15] -type PI PI
add mapped point a[14] a[14] -type PI PI
add mapped point a[13] a[13] -type PI PI
add mapped point a[12] a[12] -type PI PI
add mapped point a[11] a[11] -type PI PI
add mapped point a[10] a[10] -type PI PI
add mapped point a[9] a[9] -type PI PI
add mapped point a[8] a[8] -type PI PI
add mapped point a[7] a[7] -type PI PI
add mapped point a[6] a[6] -type PI PI
add mapped point a[5] a[5] -type PI PI
add mapped point a[4] a[4] -type PI PI
add mapped point a[3] a[3] -type PI PI
add mapped point a[2] a[2] -type PI PI
add mapped point a[1] a[1] -type PI PI
add mapped point a[0] a[0] -type PI PI
add mapped point b[31] b[31] -type PI PI
add mapped point b[30] b[30] -type PI PI
add mapped point b[29] b[29] -type PI PI
add mapped point b[28] b[28] -type PI PI
add mapped point b[27] b[27] -type PI PI
add mapped point b[26] b[26] -type PI PI
add mapped point b[25] b[25] -type PI PI
add mapped point b[24] b[24] -type PI PI
add mapped point b[23] b[23] -type PI PI
add mapped point b[22] b[22] -type PI PI
add mapped point b[21] b[21] -type PI PI
add mapped point b[20] b[20] -type PI PI
add mapped point b[19] b[19] -type PI PI
add mapped point b[18] b[18] -type PI PI
add mapped point b[17] b[17] -type PI PI
add mapped point b[16] b[16] -type PI PI
add mapped point b[15] b[15] -type PI PI
add mapped point b[14] b[14] -type PI PI
add mapped point b[13] b[13] -type PI PI
add mapped point b[12] b[12] -type PI PI
add mapped point b[11] b[11] -type PI PI
add mapped point b[10] b[10] -type PI PI
add mapped point b[9] b[9] -type PI PI
add mapped point b[8] b[8] -type PI PI
add mapped point b[7] b[7] -type PI PI
add mapped point b[6] b[6] -type PI PI
add mapped point b[5] b[5] -type PI PI
add mapped point b[4] b[4] -type PI PI
add mapped point b[3] b[3] -type PI PI
add mapped point b[2] b[2] -type PI PI
add mapped point b[1] b[1] -type PI PI
add mapped point b[0] b[0] -type PI PI
add mapped point in_valid_i in_valid_i -type PI PI
add mapped point signal_division signal_division -type PI PI
add mapped point out_ready_i out_ready_i -type PI PI

//output ports
add mapped point c[31] c[31] -type PO PO
add mapped point c[30] c[30] -type PO PO
add mapped point c[29] c[29] -type PO PO
add mapped point c[28] c[28] -type PO PO
add mapped point c[27] c[27] -type PO PO
add mapped point c[26] c[26] -type PO PO
add mapped point c[25] c[25] -type PO PO
add mapped point c[24] c[24] -type PO PO
add mapped point c[23] c[23] -type PO PO
add mapped point c[22] c[22] -type PO PO
add mapped point c[21] c[21] -type PO PO
add mapped point c[20] c[20] -type PO PO
add mapped point c[19] c[19] -type PO PO
add mapped point c[18] c[18] -type PO PO
add mapped point c[17] c[17] -type PO PO
add mapped point c[16] c[16] -type PO PO
add mapped point c[15] c[15] -type PO PO
add mapped point c[14] c[14] -type PO PO
add mapped point c[13] c[13] -type PO PO
add mapped point c[12] c[12] -type PO PO
add mapped point c[11] c[11] -type PO PO
add mapped point c[10] c[10] -type PO PO
add mapped point c[9] c[9] -type PO PO
add mapped point c[8] c[8] -type PO PO
add mapped point c[7] c[7] -type PO PO
add mapped point c[6] c[6] -type PO PO
add mapped point c[5] c[5] -type PO PO
add mapped point c[4] c[4] -type PO PO
add mapped point c[3] c[3] -type PO PO
add mapped point c[2] c[2] -type PO PO
add mapped point c[1] c[1] -type PO PO
add mapped point c[0] c[0] -type PO PO
add mapped point r[31] r[31] -type PO PO
add mapped point r[30] r[30] -type PO PO
add mapped point r[29] r[29] -type PO PO
add mapped point r[28] r[28] -type PO PO
add mapped point r[27] r[27] -type PO PO
add mapped point r[26] r[26] -type PO PO
add mapped point r[25] r[25] -type PO PO
add mapped point r[24] r[24] -type PO PO
add mapped point r[23] r[23] -type PO PO
add mapped point r[22] r[22] -type PO PO
add mapped point r[21] r[21] -type PO PO
add mapped point r[20] r[20] -type PO PO
add mapped point r[19] r[19] -type PO PO
add mapped point r[18] r[18] -type PO PO
add mapped point r[17] r[17] -type PO PO
add mapped point r[16] r[16] -type PO PO
add mapped point r[15] r[15] -type PO PO
add mapped point r[14] r[14] -type PO PO
add mapped point r[13] r[13] -type PO PO
add mapped point r[12] r[12] -type PO PO
add mapped point r[11] r[11] -type PO PO
add mapped point r[10] r[10] -type PO PO
add mapped point r[9] r[9] -type PO PO
add mapped point r[8] r[8] -type PO PO
add mapped point r[7] r[7] -type PO PO
add mapped point r[6] r[6] -type PO PO
add mapped point r[5] r[5] -type PO PO
add mapped point r[4] r[4] -type PO PO
add mapped point r[3] r[3] -type PO PO
add mapped point r[2] r[2] -type PO PO
add mapped point r[1] r[1] -type PO PO
add mapped point r[0] r[0] -type PO PO
add mapped point in_ready_o in_ready_o -type PO PO
add mapped point out_valid_o out_valid_o -type PO PO

//inout ports




//Sequential Pins
add mapped point out_valid_o/q out_valid_o_reg/Q -type DFF DFF
add mapped point Quatient[0]/q Quatient_reg[0]/Q -type DFF DFF
add mapped point Quatient[1]/q Quatient_reg[1]/Q -type DFF DFF
add mapped point Quatient[2]/q Quatient_reg[2]/Q -type DFF DFF
add mapped point Quatient[3]/q Quatient_reg[3]/Q -type DFF DFF
add mapped point Quatient[4]/q Quatient_reg[4]/Q -type DFF DFF
add mapped point Quatient[5]/q Quatient_reg[5]/Q -type DFF DFF
add mapped point Quatient[6]/q Quatient_reg[6]/Q -type DFF DFF
add mapped point Quatient[7]/q Quatient_reg[7]/Q -type DFF DFF
add mapped point Quatient[8]/q Quatient_reg[8]/Q -type DFF DFF
add mapped point Quatient[9]/q Quatient_reg[9]/Q -type DFF DFF
add mapped point Quatient[10]/q Quatient_reg[10]/Q -type DFF DFF
add mapped point Quatient[11]/q Quatient_reg[11]/Q -type DFF DFF
add mapped point Quatient[12]/q Quatient_reg[12]/Q -type DFF DFF
add mapped point Quatient[13]/q Quatient_reg[13]/Q -type DFF DFF
add mapped point Quatient[14]/q Quatient_reg[14]/Q -type DFF DFF
add mapped point Quatient[15]/q Quatient_reg[15]/Q -type DFF DFF
add mapped point Quatient[16]/q Quatient_reg[16]/Q -type DFF DFF
add mapped point Quatient[17]/q Quatient_reg[17]/Q -type DFF DFF
add mapped point Quatient[18]/q Quatient_reg[18]/Q -type DFF DFF
add mapped point Quatient[19]/q Quatient_reg[19]/Q -type DFF DFF
add mapped point Quatient[20]/q Quatient_reg[20]/Q -type DFF DFF
add mapped point Quatient[21]/q Quatient_reg[21]/Q -type DFF DFF
add mapped point Quatient[22]/q Quatient_reg[22]/Q -type DFF DFF
add mapped point Quatient[23]/q Quatient_reg[23]/Q -type DFF DFF
add mapped point Quatient[24]/q Quatient_reg[24]/Q -type DFF DFF
add mapped point Quatient[25]/q Quatient_reg[25]/Q -type DFF DFF
add mapped point Quatient[26]/q Quatient_reg[26]/Q -type DFF DFF
add mapped point Quatient[27]/q Quatient_reg[27]/Q -type DFF DFF
add mapped point Quatient[28]/q Quatient_reg[28]/Q -type DFF DFF
add mapped point Quatient[29]/q Quatient_reg[29]/Q -type DFF DFF
add mapped point Quatient[30]/q Quatient_reg[30]/Q -type DFF DFF
add mapped point Quatient[31]/q Quatient_reg[31]/Q -type DFF DFF
add mapped point a_reg[0]/q a_reg_reg[0]/Q -type DFF DFF
add mapped point a_reg[1]/q a_reg_reg[1]/Q -type DFF DFF
add mapped point a_reg[2]/q a_reg_reg[2]/Q -type DFF DFF
add mapped point a_reg[3]/q a_reg_reg[3]/Q -type DFF DFF
add mapped point a_reg[4]/q a_reg_reg[4]/Q -type DFF DFF
add mapped point a_reg[5]/q a_reg_reg[5]/Q -type DFF DFF
add mapped point a_reg[6]/q a_reg_reg[6]/Q -type DFF DFF
add mapped point a_reg[7]/q a_reg_reg[7]/Q -type DFF DFF
add mapped point a_reg[8]/q a_reg_reg[8]/Q -type DFF DFF
add mapped point a_reg[9]/q a_reg_reg[9]/Q -type DFF DFF
add mapped point a_reg[10]/q a_reg_reg[10]/Q -type DFF DFF
add mapped point a_reg[11]/q a_reg_reg[11]/Q -type DFF DFF
add mapped point a_reg[12]/q a_reg_reg[12]/Q -type DFF DFF
add mapped point a_reg[13]/q a_reg_reg[13]/Q -type DFF DFF
add mapped point a_reg[14]/q a_reg_reg[14]/Q -type DFF DFF
add mapped point a_reg[15]/q a_reg_reg[15]/Q -type DFF DFF
add mapped point a_reg[16]/q a_reg_reg[16]/Q -type DFF DFF
add mapped point a_reg[17]/q a_reg_reg[17]/Q -type DFF DFF
add mapped point a_reg[18]/q a_reg_reg[18]/Q -type DFF DFF
add mapped point a_reg[19]/q a_reg_reg[19]/Q -type DFF DFF
add mapped point a_reg[20]/q a_reg_reg[20]/Q -type DFF DFF
add mapped point a_reg[21]/q a_reg_reg[21]/Q -type DFF DFF
add mapped point a_reg[22]/q a_reg_reg[22]/Q -type DFF DFF
add mapped point a_reg[23]/q a_reg_reg[23]/Q -type DFF DFF
add mapped point a_reg[24]/q a_reg_reg[24]/Q -type DFF DFF
add mapped point a_reg[25]/q a_reg_reg[25]/Q -type DFF DFF
add mapped point a_reg[26]/q a_reg_reg[26]/Q -type DFF DFF
add mapped point a_reg[27]/q a_reg_reg[27]/Q -type DFF DFF
add mapped point a_reg[28]/q a_reg_reg[28]/Q -type DFF DFF
add mapped point a_reg[29]/q a_reg_reg[29]/Q -type DFF DFF
add mapped point a_reg[30]/q a_reg_reg[30]/Q -type DFF DFF
add mapped point a_reg[31]/q a_reg_reg[31]/Q -type DFF DFF
add mapped point a_signal/q a_signal_reg/Q -type DFF DFF
add mapped point b_reg[0]/q b_reg_reg[0]/Q -type DFF DFF
add mapped point b_reg[1]/q b_reg_reg[1]/Q -type DFF DFF
add mapped point b_reg[2]/q b_reg_reg[2]/Q -type DFF DFF
add mapped point b_reg[3]/q b_reg_reg[3]/Q -type DFF DFF
add mapped point b_reg[4]/q b_reg_reg[4]/Q -type DFF DFF
add mapped point b_reg[5]/q b_reg_reg[5]/Q -type DFF DFF
add mapped point b_reg[6]/q b_reg_reg[6]/Q -type DFF DFF
add mapped point b_reg[7]/q b_reg_reg[7]/Q -type DFF DFF
add mapped point b_reg[8]/q b_reg_reg[8]/Q -type DFF DFF
add mapped point b_reg[9]/q b_reg_reg[9]/Q -type DFF DFF
add mapped point b_reg[10]/q b_reg_reg[10]/Q -type DFF DFF
add mapped point b_reg[11]/q b_reg_reg[11]/Q -type DFF DFF
add mapped point b_reg[12]/q b_reg_reg[12]/Q -type DFF DFF
add mapped point b_reg[13]/q b_reg_reg[13]/Q -type DFF DFF
add mapped point b_reg[14]/q b_reg_reg[14]/Q -type DFF DFF
add mapped point b_reg[15]/q b_reg_reg[15]/Q -type DFF DFF
add mapped point b_reg[16]/q b_reg_reg[16]/Q -type DFF DFF
add mapped point b_reg[17]/q b_reg_reg[17]/Q -type DFF DFF
add mapped point b_reg[18]/q b_reg_reg[18]/Q -type DFF DFF
add mapped point b_reg[19]/q b_reg_reg[19]/Q -type DFF DFF
add mapped point b_reg[20]/q b_reg_reg[20]/Q -type DFF DFF
add mapped point b_reg[21]/q b_reg_reg[21]/Q -type DFF DFF
add mapped point b_reg[22]/q b_reg_reg[22]/Q -type DFF DFF
add mapped point b_reg[23]/q b_reg_reg[23]/Q -type DFF DFF
add mapped point b_reg[24]/q b_reg_reg[24]/Q -type DFF DFF
add mapped point b_reg[25]/q b_reg_reg[25]/Q -type DFF DFF
add mapped point b_reg[26]/q b_reg_reg[26]/Q -type DFF DFF
add mapped point b_reg[27]/q b_reg_reg[27]/Q -type DFF DFF
add mapped point b_reg[28]/q b_reg_reg[28]/Q -type DFF DFF
add mapped point b_reg[29]/q b_reg_reg[29]/Q -type DFF DFF
add mapped point b_reg[30]/q b_reg_reg[30]/Q -type DFF DFF
add mapped point b_reg[31]/q b_reg_reg[31]/Q -type DFF DFF
add mapped point b_signal/q b_signal_reg/Q -type DFF DFF
add mapped point ena/q ena_reg/Q -type DFF DFF
add mapped point in_ready_o/q in_ready_o_reg/Q -type DFF DFF
add mapped point k[0]/q k_reg[0]/Q -type DFF DFF
add mapped point k[1]/q k_reg[1]/Q -type DFF DFF
add mapped point k[2]/q k_reg[2]/Q -type DFF DFF
add mapped point k[3]/q k_reg[3]/Q -type DFF DFF
add mapped point k[4]/q k_reg[4]/Q -type DFF DFF
add mapped point minuend[0]/q minuend_reg[0]/Q -type DFF DFF
add mapped point minuend[1]/q minuend_reg[1]/Q -type DFF DFF
add mapped point minuend[2]/q minuend_reg[2]/Q -type DFF DFF
add mapped point minuend[3]/q minuend_reg[3]/Q -type DFF DFF
add mapped point minuend[4]/q minuend_reg[4]/Q -type DFF DFF
add mapped point minuend[5]/q minuend_reg[5]/Q -type DFF DFF
add mapped point minuend[6]/q minuend_reg[6]/Q -type DFF DFF
add mapped point minuend[7]/q minuend_reg[7]/Q -type DFF DFF
add mapped point minuend[8]/q minuend_reg[8]/Q -type DFF DFF
add mapped point minuend[9]/q minuend_reg[9]/Q -type DFF DFF
add mapped point minuend[10]/q minuend_reg[10]/Q -type DFF DFF
add mapped point minuend[11]/q minuend_reg[11]/Q -type DFF DFF
add mapped point minuend[12]/q minuend_reg[12]/Q -type DFF DFF
add mapped point minuend[13]/q minuend_reg[13]/Q -type DFF DFF
add mapped point minuend[14]/q minuend_reg[14]/Q -type DFF DFF
add mapped point minuend[15]/q minuend_reg[15]/Q -type DFF DFF
add mapped point minuend[16]/q minuend_reg[16]/Q -type DFF DFF
add mapped point minuend[17]/q minuend_reg[17]/Q -type DFF DFF
add mapped point minuend[18]/q minuend_reg[18]/Q -type DFF DFF
add mapped point minuend[19]/q minuend_reg[19]/Q -type DFF DFF
add mapped point minuend[20]/q minuend_reg[20]/Q -type DFF DFF
add mapped point minuend[21]/q minuend_reg[21]/Q -type DFF DFF
add mapped point minuend[22]/q minuend_reg[22]/Q -type DFF DFF
add mapped point minuend[23]/q minuend_reg[23]/Q -type DFF DFF
add mapped point minuend[24]/q minuend_reg[24]/Q -type DFF DFF
add mapped point minuend[25]/q minuend_reg[25]/Q -type DFF DFF
add mapped point minuend[26]/q minuend_reg[26]/Q -type DFF DFF
add mapped point minuend[27]/q minuend_reg[27]/Q -type DFF DFF
add mapped point minuend[28]/q minuend_reg[28]/Q -type DFF DFF
add mapped point minuend[29]/q minuend_reg[29]/Q -type DFF DFF
add mapped point minuend[30]/q minuend_reg[30]/Q -type DFF DFF
add mapped point minuend[31]/q minuend_reg[31]/Q -type DFF DFF
add mapped point signal_division_intern/q signal_division_intern_reg/Q -type DFF DFF
add mapped point state[0]/q state_reg[0]/Q -type DFF DFF
add mapped point state[1]/q state_reg[1]/Q -type DFF DFF
add mapped point state[2]/q state_reg[2]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
