#
# Voltus Scheduler command file generated by voltus_rail on Wed Dec  3 22:39:26 2025
#
setvar log_file ./work/voltus_extractor_VDD.log 
setvar output_cache_directory_name /tmp/innovus_temp_339229_VT0138_xmen_XLkF9E/zx_tmp_VT0138_350663
setvar library_name ./run1/era_work/incremental_output1/pgv/techonly.cl
setvar output_directory_name ./work
setvar output_file_name VDD 
setvar max_error_messages 100
setvar max_resistor_length 800
setvar hierarchy_char /
layout_file /tmp/innovus_temp_339229_VT0138_xmen_XLkF9E/eps_out_339229.def.gz
setvar exec_token "/tmp/innovus_temp_339229_VT0138_xmen_XLkF9E/eps_out_339229.def.gz"
setvar enable_signal_via_overhang false
setvar zx_multinet_extraction false
setvar extraction_mode early
setvar enable_zx_report_shorts true
extraction_type all none
extraction_type pattern {VDD} r_only 
hierarchical_path_tracer netinst_table ./work/VDD.netinst 
hierarchical_path_tracer cell_table ./work/VDD.cellinst 
setvar output_wlt drawn
setvar use_hpt_leqnets_info true
label port VDDvsrc1 0.6650 12.5950 Metal10
hierarchical_path_tracer pgnet_table ./work/all.pgnets
setvar output_def false
setvar cluster_via_size 25
setvar cluster_via1_maximum true
setvar def_merge_supply_shorts false
setvar promote_ports true
setvar max_cpu 1
setvar tech_file ../QRC_TECH/gpdk045.tch
setvar density_check_method database
setvar sfedb_path ./work/SFEDB
setvar enable_binary_inst_pgdb true
setvar keep_log_file false
