###############################################################
#  Generated by:      Cadence Innovus 21.19-s058_1
#  OS:                Linux x86_64(Host ID VT0138)
#  Generated on:      Wed Dec  3 21:59:36 2025
#  Design:            opdiv
#  Command:           write_db place0pt
###############################################################
current_design opdiv
set_clock_gating_check -rise -setup 0 
set_clock_gating_check -fall -setup 0 
set_wire_load_mode enclosed
